# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_models', '0002_auto_20180124_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='learned_lessons',
            field=models.ManyToManyField(blank=True, to='web_app_models.Lesson', verbose_name='Пройденные тесты'),
        ),
    ]
