# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_models', '0003_auto_20180124_1136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Библиотека'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Медиапроект', 'verbose_name_plural': 'Медиапроекты'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
