# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-29 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_models', '0005_auto_20180125_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина')], default='male', max_length=255, null=True, verbose_name='Пол'),
        ),
    ]
