# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_models', '0007_auto_20180129_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageslide',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя слайдера'),
        ),
    ]
