# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-03 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_models', '0009_auto_20180201_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Файл'),
        ),
    ]
