# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-03 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_models', '0010_auto_20180203_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='preview',
            field=models.ImageField(upload_to='', verbose_name='Превью работы'),
        ),
    ]
