# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-22 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_models', '0013_auto_20180221_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseanswer',
            name='true_choice',
            field=models.CharField(blank=True, choices=[('1', 'Первый вариант ответа'), ('2', 'Второй вариант ответа')], help_text='Здесь вы выбираете вариант ответа который укзали ранее, только если вы выбрали типом вопросв "Сопоставление"', max_length=255, null=True, verbose_name='Относится к варианту'),
        ),
    ]
