# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-04 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_models', '0014_exerciseanswer_true_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.URLField(blank=True, help_text='Заполнять лишь в том случае, когда вы не загрузили файл', null=True, verbose_name='Ссылка на ресурс'),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл'),
        ),
    ]
