# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 08:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_models', '0017_auto_20180320_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Проценты')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app_models.Lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.AlterModelOptions(
            name='mediaprojectsslider',
            options={'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайдер на странице медиапроектов'},
        ),
        migrations.RemoveField(
            model_name='users',
            name='learned_lessons',
        ),
        migrations.AlterField(
            model_name='exercisequestion',
            name='first_association',
            field=models.CharField(blank=True, help_text='Это поле заполняется только в случае если вариантом вопроса вы выбрали "Сопоставление", оно будет отображаться как один из возможных ответов', max_length=255, null=True, verbose_name='Первый вариант ответа'),
        ),
        migrations.AlterField(
            model_name='exercisequestion',
            name='second_association',
            field=models.CharField(blank=True, help_text='Это поле заполняется только в случае если вариантом вопроса вы выбрали "Сопоставление", оно будет отображаться как один из возможных ответов', max_length=255, null=True, verbose_name='Второй вариант ответа'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='first_association',
            field=models.CharField(blank=True, help_text='Это поле заполняется только в случае если вариантом вопроса вы выбрали "Сопоставление", оно будет отображаться как один из возможных ответов', max_length=255, null=True, verbose_name='Первый вариант ответа'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='second_association',
            field=models.CharField(blank=True, help_text='Это поле заполняется только в случае если вариантом вопроса вы выбрали "Сопоставление", оно будет отображаться как один из возможных ответов', max_length=255, null=True, verbose_name='Второй вариант ответа'),
        ),
        migrations.AddField(
            model_name='results',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
