# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_models', '0018_auto_20180404_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='learned_lessons',
            field=models.ManyToManyField(blank=True, to='web_app_models.Lesson', verbose_name='Пройденные тесты'),
        ),
        migrations.AlterField(
            model_name='results',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app_models.Test', verbose_name='Урок'),
        ),
    ]
