# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_models', '0019_auto_20180404_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='point',
            field=models.PositiveIntegerField(verbose_name='Проценты'),
        ),
    ]
