# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_models', '0021_results_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='point',
            field=models.PositiveIntegerField(null=True, verbose_name='Проценты'),
        ),
    ]
