# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-27 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_models', '0023_aboutus_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Раздел')),
                ('image', models.ImageField(upload_to='images/parts', verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': 'Разделы',
                'verbose_name': 'Раздел',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part', to='web_app_models.Part', verbose_name='Раздел'),
        ),
    ]
